//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RS_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Застройщик.
    /// </summary>
    //  *** Start programmer edit section *** (Застройщик CustomAttributes)

    //  *** End programmer edit section *** (Застройщик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗастройщикE", new string[] {
            "Основной as \'Основной\'",
            "Застройщик as \'Застройщик\'",
            "Застройщик.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Застройщик.Наименование"})]
    [MasterViewDefineAttribute("ЗастройщикE", "Застройщик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Застройщик : ICSSoft.STORMNET.DataObject
    {
        
        private bool fОсновной;
        
        private IIS.RS_2.Организация fОрганизЗастр;
        
        private IIS.RS_2.РазрешНаСтроит fРазрешение;
        
        //  *** Start programmer edit section *** (Застройщик CustomMembers)

        //  *** End programmer edit section *** (Застройщик CustomMembers)

        
        /// <summary>
        /// Основной.
        /// </summary>
        //  *** Start programmer edit section *** (Застройщик.Основной CustomAttributes)

        //  *** End programmer edit section *** (Застройщик.Основной CustomAttributes)
        public virtual bool Основной
        {
            get
            {
                //  *** Start programmer edit section *** (Застройщик.Основной Get start)

                //  *** End programmer edit section *** (Застройщик.Основной Get start)
                bool result = this.fОсновной;
                //  *** Start programmer edit section *** (Застройщик.Основной Get end)

                //  *** End programmer edit section *** (Застройщик.Основной Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Застройщик.Основной Set start)

                //  *** End programmer edit section *** (Застройщик.Основной Set start)
                this.fОсновной = value;
                //  *** Start programmer edit section *** (Застройщик.Основной Set end)

                //  *** End programmer edit section *** (Застройщик.Основной Set end)
            }
        }
        
        /// <summary>
        /// Застройщик.
        /// </summary>
        //  *** Start programmer edit section *** (Застройщик.ОрганизЗастр CustomAttributes)

        //  *** End programmer edit section *** (Застройщик.ОрганизЗастр CustomAttributes)
        [NotNull()]
        public virtual IIS.RS_2.Организация ОрганизЗастр
        {
            get
            {
                //  *** Start programmer edit section *** (Застройщик.ОрганизЗастр Get start)

                //  *** End programmer edit section *** (Застройщик.ОрганизЗастр Get start)
                IIS.RS_2.Организация result = this.fОрганизЗастр;
                //  *** Start programmer edit section *** (Застройщик.ОрганизЗастр Get end)

                //  *** End programmer edit section *** (Застройщик.ОрганизЗастр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Застройщик.ОрганизЗастр Set start)

                //  *** End programmer edit section *** (Застройщик.ОрганизЗастр Set start)
                this.fОрганизЗастр = value;
                //  *** Start programmer edit section *** (Застройщик.ОрганизЗастр Set end)

                //  *** End programmer edit section *** (Застройщик.ОрганизЗастр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.RS_2.РазрешНаСтроит.
        /// </summary>
        //  *** Start programmer edit section *** (Застройщик.Разрешение CustomAttributes)

        //  *** End programmer edit section *** (Застройщик.Разрешение CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.RS_2.РазрешНаСтроит Разрешение
        {
            get
            {
                //  *** Start programmer edit section *** (Застройщик.Разрешение Get start)

                //  *** End programmer edit section *** (Застройщик.Разрешение Get start)
                IIS.RS_2.РазрешНаСтроит result = this.fРазрешение;
                //  *** Start programmer edit section *** (Застройщик.Разрешение Get end)

                //  *** End programmer edit section *** (Застройщик.Разрешение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Застройщик.Разрешение Set start)

                //  *** End programmer edit section *** (Застройщик.Разрешение Set start)
                this.fРазрешение = value;
                //  *** Start programmer edit section *** (Застройщик.Разрешение Set end)

                //  *** End programmer edit section *** (Застройщик.Разрешение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗастройщикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗастройщикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗастройщикE", typeof(IIS.RS_2.Застройщик));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Застройщик.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfЗастройщик CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfЗастройщик CustomAttributes)
    public class DetailArrayOfЗастройщик : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.RS_2.DetailArrayOfЗастройщик members)

        //  *** End programmer edit section *** (IIS.RS_2.DetailArrayOfЗастройщик members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Застройщик by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Застройщик.
        /// </summary>
        public DetailArrayOfЗастройщик(IIS.RS_2.РазрешНаСтроит fРазрешНаСтроит) : 
                base(typeof(Застройщик), ((ICSSoft.STORMNET.DataObject)(fРазрешНаСтроит)))
        {
        }
        
        public IIS.RS_2.Застройщик this[int index]
        {
            get
            {
                return ((IIS.RS_2.Застройщик)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.RS_2.Застройщик dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
