//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RS_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    //  *** Start programmer edit section *** (Организация CustomAttributes)

    //  *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fАдрес;
        
        private string fИНН;
        
        //  *** Start programmer edit section *** (Организация CustomMembers)

        //  *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Организация.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Организация.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Организация.Наименование Get start)

                //  *** End programmer edit section *** (Организация.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Организация.Наименование Get end)

                //  *** End programmer edit section *** (Организация.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Организация.Наименование Set start)

                //  *** End programmer edit section *** (Организация.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Организация.Наименование Set end)

                //  *** End programmer edit section *** (Организация.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (Организация.Адрес CustomAttributes)

        //  *** End programmer edit section *** (Организация.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (Организация.Адрес Get start)

                //  *** End programmer edit section *** (Организация.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (Организация.Адрес Get end)

                //  *** End programmer edit section *** (Организация.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Организация.Адрес Set start)

                //  *** End programmer edit section *** (Организация.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (Организация.Адрес Set end)

                //  *** End programmer edit section *** (Организация.Адрес Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        //  *** Start programmer edit section *** (Организация.ИНН CustomAttributes)

        //  *** End programmer edit section *** (Организация.ИНН CustomAttributes)
        [StrLen(255)]
        public virtual string ИНН
        {
            get
            {
                //  *** Start programmer edit section *** (Организация.ИНН Get start)

                //  *** End programmer edit section *** (Организация.ИНН Get start)
                string result = this.fИНН;
                //  *** Start programmer edit section *** (Организация.ИНН Get end)

                //  *** End programmer edit section *** (Организация.ИНН Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Организация.ИНН Set start)

                //  *** End programmer edit section *** (Организация.ИНН Set start)
                this.fИНН = value;
                //  *** Start programmer edit section *** (Организация.ИНН Set end)

                //  *** End programmer edit section *** (Организация.ИНН Set end)
            }
        }
    }
}
